apiVersion: v1
kind: Service
metadata:
  name: td-api
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: td-api
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: td-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: td-api
    spec:
      containers:
        # [START esp]
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http_port=8081",
            "--backend=127.0.0.1:8080",
            "--service=animaltypes.endpoints.gdos-mdonahue-sb.cloud.goog,specimentypes.endpoints.gdos-mdonahue-sb.cloud.goog",
            "--rollout_strategy=managed",
          ]
          # [END esp]
          ports:
            - containerPort: 8081
        - name: api
          image: gcr.io/gdos-mdonahue-sb/testdirectory-api:127716787297511
          ports:
            - containerPort: 8080
